[project]
name = "rebuildr"
version = "0.1.0"
description = ""
requires-python = ">=3.12"
authors = [{ name = "Paweł Chojnacki", email = "pawelchcki@gmail.com" }]
dependencies = ["typer >= 0.15.1"]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project.scripts]
rebuildr = "rebuildr.cli:app"
