name: Quick checks without matrix computation
on:
  push:
jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@786fff0690178f1234e4e1fe9b536e94f5433196 # v20
      - name: Quick format check
        run: |
          nix fmt
          if ! git diff --quiet; then
            echo "❌ Code formatting issues found. Please run 'nix fmt' to fix them."
            git diff
            exit 1
          fi
          echo "✅ Code formatting is correct"
      - name: Quick test
        run: nix flake check
      - name: Quick build
        run: nix build .#packages.x86_64-linux.default
