name: Quick checks without matrix computation
on:
  push:
    branches: [main, master]
  pull_request:
    branches: [main, master]
  workflow_dispatch:
jobs:
  quick-check:
    name: Quick Check
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install Nix
        uses: DeterminateSystems/nix-installer-action@v9
      - name: Quick format check
        run: |
          nix fmt
          if ! git diff --quiet; then
            echo "❌ Code formatting issues found. Please run 'nix fmt' to fix them."
            git diff
            exit 1
          fi
          echo "✅ Code formatting is correct"
      - name: Quick test
        run: nix flake check
      - name: Quick build
        run: nix build .#packages.x86_64-linux.default
