name: Publish dist image on tag

on:
  push:
    tags:
      - '*'

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-dist:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up QEMU (for multi-arch, optional)
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push dist image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ci/dist/dist.Dockerfile
          push: true
          tags: |
            ghcr.io/pawelchcki/rebuildr/dist:${{ github.ref_name }}
            ghcr.io/pawelchcki/rebuildr/dist:latest